cmd_net.c: fix build breakage
From: Wolfgang Denk <wd@denx.de>

Commit 722b061 "autocomplete: remove runtime handler install" caused
some boards (like NETTA2_V2) to break with errors like these:

cmd_net.c:296: error: expected expression before ',' token

Fix this.


git-svn-id: svn://localhost/svn/u-boot/trunk@2580 e8ad1c53-384c-47db-b5ce-66ae1f620dea